#CARGA DE DATOS DESDE CSV


f <- file.choose()
df <- read.csv(f, , stringsAsFactors=T, header = TRUE, sep=",")

###df <- read.csv("base-covid-sinave-2 31012021.csv", stringsAsFactors=T, header = TRUE, sep=",")""


#EXPLORACION DE DATOS
class(df)
head(df)
str(df)
summary(df)



####LIMPIEZA y PREPARACION DE DATOS####

#FILTRAR DATOS SARS-CoV-2 EN VARIABLE resultado_definitivo
library(dplyr)


df2 <- df %>%
  mutate(fecha_de_registro = as.Date(fecha_de_registro)) %>%
  filter(resultado_definitivo == "SARS-CoV-2", rango_de_edad != "", fecha_de_registro >= 2020-01-01)%>%
  droplevels()

levels(df2$evolucion_caso)



####REPRESENTAMOS LA VARIABLE "EVOLUCION DEL CASO" POR SEXO####

#Representación en gráfico de barras. Para agregar etiquetas con proporciones de columnas, lo primero que debe hacer es crear otro dato que resuma la proporción de columnas.


#AGRUPAR NIVELES EN 4; RECUPERADOS, ACTIVOS GRAVES, ACTIVOS LEVES, DEFUNCION"

df2$evolucion_caso
levels(df2$evolucion_caso) <-c("RECUPERADOS", "RECUPERADOS", "RECUPERADOS", "RECUPERADOS", "ACTIVOS GRAVES", "ACTIVOS GRAVES", "ACTIVOS LEVES", "FALLECIDOS", "ACTIVOS LEVES", "ACTIVOS LEVES", "ACTIVOS LEVES", "RECUPERADOS")


percentData <- df2 %>% group_by(evolucion_caso) %>% count(sexo) %>%
  mutate(ratio=scales::percent(n/sum(n)))

library(ggplot2)

ggplot(data=df2, aes(x=evolucion_caso, fill=sexo)) + 
  geom_bar() +
  geom_text(data=percentData, aes(y=n,label=ratio), position=position_stack(0.5), size=3) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


percentData2 <- df2 %>% group_by(evolucion_caso) %>% count(evolucion_caso)
percentData2

percentData3 <- df2 %>% group_by(evolucion_caso,rango_de_edad) %>% count(sexo) %>%
  mutate(ratio=scales::percent(n/sum(n)))

percentData3

ggplot(df2, aes(x=rango_de_edad, y=sexo, fill=sexo)) +
  geom_bar(stat = "count", data=df2[df2$sexo=="MASCULINO",], mapping = aes(y = (..count..))) +
  geom_text(data=percentData3[percentData3$sexo=="MASCULINO",], aes(y = n, label = ratio), size = 2.5, position = position_fill(vjust = 0.5), hjust = -0.3) +
  geom_bar(stat = "count", df2[df2$sexo=="FEMENINO",], mapping = aes(y= -(..count..))) +
  geom_text(data=percentData3[percentData3$sexo=="FEMENINO",], aes(y = -n, label = ratio), size = 2.5, position = position_fill(vjust = 0.5), hjust = 1.3)+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  scale_y_continuous(label= abs) +
  coord_flip() + 
  theme(text = element_text(size=10))+
  labs(y="Porcentaje", x="Rango de Edad") +
  ggtitle("EVOLUCION DEL CASO")

summary(df2$evolucion_caso)


####REPRESENTAMOS LA VARIABLE "EVOLUCION DEL CASO" POR PATOLOGIA####


#DISTRIBUCION DE DEFUNCION POR EDAD PARA DIABETES

ggplot(df2, aes(x=rango_de_edad, y=diabetes)) +
  geom_bar(stat = "count", data=df2[df2$diabetes=="SI",], mapping = aes(y = (..count..)), fill="#154360") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: DIABETES")

#DISTRIBUCION DE DEFUNCION POR EDAD PARA EPOC

ggplot(df2, aes(x=rango_de_edad, y=epoc)) +
  geom_bar(stat = "count", data=df2[df2$epoc=="SI",], mapping = aes(y = (..count..)), fill="#B9770E") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: EPOC")



#DISTRIBUCION DE DEFUNCION POR EDAD PARA ASMA

ggplot(df2, aes(x=rango_de_edad, y=asma)) +
  geom_bar(stat = "count", data=df2[df2$asma=="SI",], mapping = aes(y = (..count..)), fill="#58D68D") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: ASMA")
  


#DISTRIBUCION DE DEFUNCION POR EDAD PARA INMUNODEPRESIVO

ggplot(df2, aes(x=rango_de_edad, y=inmunosupresivo)) +
  geom_bar(stat = "count", data=df2[df2$inmunosupresivo =="SI",], mapping = aes(y = (..count..)), fill="#C39BD3") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: INMUNSUPRESIVO")



#DISTRIBUCION DE DEFUNCION POR EDAD PARA HIPERTENSION

ggplot(df2, aes(x=rango_de_edad, y=hipertension)) +
  geom_bar(stat = "count", data=df2[df2$hipertension =="SI",], mapping = aes(y = (..count..)), fill="#F7DC6F") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: HIPERTENSION")


#DISTRIBUCION DE DEFUNCION POR EDAD PARA VIH_SIDA

ggplot(df2, aes(x=rango_de_edad, y=VIH_SIDA)) +
  geom_bar(stat = "count", data=df2[df2$VIH_SIDA =="SI",], mapping = aes(y = (..count..)), fill="#45B39D") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: VIH_SIDA")


#DISTRIBUCION DE DEFUNCION POR EDAD PARA OTRA CONDICION

ggplot(df2, aes(x=rango_de_edad, y=otra_condicion)) +
  geom_bar(stat = "count", data=df2[df2$otra_condicion =="SI",], mapping = aes(y = (..count..)), fill="#808B96") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: OTRA CONDICION")


#DISTRIBUCION DE DEFUNCION POR EDAD PARA ENFERMEDAD CARDIACA

ggplot(df2, aes(x=rango_de_edad, y=enfermedad_cardiaca)) +
  geom_bar(stat = "count", data=df2[df2$enfermedad_cardiaca =="SI",], mapping = aes(y = (..count..)), fill="#FF007F") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: ENFERMEDAD CARDIACA")


#DISTRIBUCION DE DEFUNCION POR EDAD PARA ENFERMEDAD OBESIDAD

ggplot(df2, aes(x=rango_de_edad, y=obesidad)) +
  geom_bar(stat = "count", data=df2[df2$obesidad =="SI",], mapping = aes(y = (..count..)), fill="#EC7063") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: ENFERMEDAD OBESIDAD") 


ggplot(data=df_obesidad , aes(x=rango_de_edad, y=n)) +
  geom_bar(stat="identity", fill="#EC7063")+
  geom_text(aes(label=ratio), vjust=-0.9, color="black", size=3)+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("OBESIDAD")


#DISTRIBUCION DE DEFUNCION POR EDAD PARA INSUFICIENCIA RENAL CRONICA

ggplot(df2, aes(x=rango_de_edad, y=insuficiencia_renal_cronica)) +
  geom_bar(stat = "count", data=df2[df2$insuficiencia_renal_cronica =="SI",], mapping = aes(y = (..count..)), fill="#A8B627") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: INSUFICIENCIA RENAL CRONICA") 


#DISTRIBUCION DE DEFUNCION POR EDAD PARA TABAQUISMO

ggplot(df2, aes(x=rango_de_edad, y=tabaquismo)) +
  geom_bar(stat = "count", data=df2[df2$tabaquismo =="SI",], mapping = aes(y = (..count..)), fill="#D2B4DE") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("EVOLUCION DEL CASO: TABAQUISMO") 


##### DISTRIBUCION POR EVOLUCION DEL CASO Y PATOLOGIAS ####

which( colnames(df2)=="diabetes" )
which( colnames(df2)=="tabaquismo" )

install.packages("tidyr")
library("tidyr")


#Agrupamos las columnas de patologías bajo una misma variable "patologias"
df3 <- df2 %>%
  pivot_longer(cols = 51:61, names_to = "patologias") %>%
  filter(value == "SI")%>%
  mutate(patologias = forcats::fct_relevel(patologias,"hipertension", "obesidad","diabetes","tabaquismo","enfermedad_cardiaca","asma","insuficiencia_renal_cronica","epoc","otra_condicion", "inmunosupresivo","VIH_SIDA"))


#PATOLOGIAS RECUPERADOS

ggplot(data=df3, aes(y=evolucion_caso, x=rango_de_edad, fill = patologias)) + 
geom_bar(stat="count", data=df3[df3$evolucion_caso == "RECUPERADOS",], mapping = aes(y = (..count..))) +
facet_wrap(~patologias, ncol = 2) +
theme(text = element_text(size=12))+
labs(y="Casos", x="")+
ggtitle("Distribución de los RECUPERADOS") + 
theme(axis.text.x = element_text(angle = 45, hjust = 1))


# PATOLOGIAS DEFUNCION

ggplot(data=df3, aes(y=evolucion_caso, x=rango_de_edad, fill = patologias)) + 
  geom_bar(stat="count", data=df3[df3$evolucion_caso == "FALLECIDOS",], mapping = aes(y = (..count..))) +
  facet_wrap(~patologias, ncol = 2) +
  theme(text = element_text(size=13))+
  ggtitle("Distribución de los FALLECIDOS") + 
  labs(y="Casos", x="")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# PATOLOGIAS ACTIVOS GRAVES

ggplot(data=df3, aes(y=evolucion_caso, x=rango_de_edad, fill = patologias)) + 
  geom_bar(stat="count", data=df3[df3$evolucion_caso == "ACTIVOS GRAVES",], mapping = aes(y = (..count..))) +
  facet_wrap(~patologias, ncol = 2) +
  theme(text = element_text(size=11))+
  ggtitle("Distribución de los ACTIVOS GRAVES") + 
  labs(y="Casos", x="")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


# PATOLOGIAS ACTIVOS

ggplot(data=df3, aes(y=evolucion_caso, x=rango_de_edad, fill = patologias)) + 
  geom_bar(stat="count", data=df3[df3$evolucion_caso == "ACTIVOS LEVES",], mapping = aes(y = (..count..))) +
  facet_wrap(~patologias, ncol = 2) +
  theme(text = element_text(size=11))+
  ggtitle("Distribución de los ACTIVOS LEVES") + 
  labs(y="Casos", x="")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

col_count(df3, diabetes:tabaquismo, count = 'SI', append = TRUE)


####PESO DE CADA PATOLOGIA PARA PARA CADA EVOLUCION DEL CASO####

#PESO DE CADA PATOLOGIA PARA LOS PACIENTES RECUPERADOS

library(scales)

PatologiasRecuperados <- df3 %>%
  filter(evolucion_caso == "RECUPERADOS")%>%
  droplevels()


PatologiasREC<- PatologiasRecuperados %>%count(patologias) %>%
  mutate(ratio=scales::percent(n/sum(n), round(2)))

PatologiasREC

ggplot(PatologiasREC, aes(x=reorder(patologias,-n),y=n,label=ratio,fill=patologias)) +
  geom_bar(stat='identity') +
  geom_text(data=PatologiasREC, aes(y=n,label=ratio), position=position_stack(0.5), size=3) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


#PESO DE CADA PATOLOGIA PARA LOS PACIENTES FALLECIDOS

PatologiasDefuncion <- df3 %>%
  filter(evolucion_caso == "FALLECIDOS")%>%
  droplevels()


PatologiasDEF<- PatologiasDefuncion %>%count(patologias) %>%
  mutate(ratio=scales::percent(n/sum(n), round(2)))

ggplot(PatologiasDEF, aes(x=reorder(patologias,-n),y=n,label=ratio,fill=patologias)) +
  geom_bar(stat='identity') +
  geom_text(data=PatologiasDEF, aes(y=n,label=ratio), position=position_stack(0.5), size=3) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


PatologiasDEF


#### DISTRIBUCION DE LOS CASOS POR EDAD #####

ggplot(df2, aes(x=rango_de_edad)) +
  geom_bar(stat = "count", data=df2, mapping = aes(y = (..count..)), fill="#5F9EA0") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  geom_hline(yintercept=0, colour="white", lwd=1) +
  facet_wrap(~evolucion_caso, ncol = 2)+
  labs(y="Casos", x="Edad")+
  theme(text = element_text(size=13))+
  ggtitle("DISTRIBUCION DE LOS CASOS POR EDAD") 